runtime: python27
api_version: 1
threadsafe: false

env_variables:
  DST_URL: 'http://example.com'

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /sitemap\.xml
  static_files: sitemap.xml
  upload: sitemap\.xml
- url: /sitemap_index\.xml
  static_files: sitemap_index.xml
  upload: sitemap_index\.xml
- url: /.*
  script: main.py
